# Generated by Django 6.0.1 on 2026-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
