# Generated by Django 6.0.1 on 2026-04-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shippingaddress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_3d',
            field=models.FileField(blank=True, null=True, upload_to='products/3d/'),
        ),
    ]
