# Generated by Django 6.0.1 on 2026-04-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_product_3d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_3d',
        ),
    ]
