# Generated by Django 6.0.1 on 2026-04-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
