"""
Django settings for swift project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import MEDIA_URL, MEDIA_ROOT
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--)2pdc@yjlg(=%idnb-7%1gl1a_!i5kv)#yfwgxyi^bi4g*0f&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',

]
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'swift.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'swift.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True

USE_I18N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

RAZORPAY_KEY_ID = "rzp_test_SKHW9WnwbTThRE"
RAZORPAY_KEY_SECRET = "YC9QpTchT25brPn0IfCpyCXX"

JAZZMIN_SETTINGS = {
    # 🔥 BRANDING
    "site_title": "Shoe Admin",
    "site_header": "Shoe Store",
    "site_brand": "Admin Panel",
    "login_logo_classes": "img-fluid",
    # 🔥 Logo
    "site_logo": "assets/img/logo.png",

    # 🔹 Small logo (sidebar collapsed)
    "site_logo_classes": "img-circle",

    # 🔹 Login page logo
    "login_logo": "assets/img/sm logo.jpg",

    # 🔹 Optional (dark mode logo)
    "site_logo_dark": "assets/img/logo.png",

    # 📌 SIDEBAR CUSTOMIZATION
    "show_sidebar": True,
    "navigation_expanded": True,

    "custom_links": {
        "core": [
            {
                "name": "Dashboard",
                "url": "admin:dashboard",
                "icon": "fas fa-chart-line",
            },
        ]
    },
    # 🔥 ORDER & GROUPING
    "order_with_respect_to": [
        "auth",
        "core",

    ],

    # 🎯 CUSTOM ICONS (VERY IMPORTANT FOR PREMIUM LOOK)
    "icons": {
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",

        "core.Product": "fas fa-shoe-prints",
        "core.Category": "fas fa-list",
        "core.Order": "fas fa-shopping-cart",
        "core.OrderItem": "fas fa-box",
        "core.Cart": "fas fa-cart-plus",
        "core.ProductSize": "fas fa-ruler",
        "core.Contact": "fas fa-envelope",
        "core.Profile": "fas fa-user-circle",
    },

    # 🚫 HIDE MODELS (if you don’t want to show)

    # 🔗 CUSTOM LINKS (ADD YOUR DASHBOARD)

    "custom_css": "css/admin.css",
}
